const axios = require('axios');

module.exports = {
  name: "ai",
  alias: ["gpt", "chatgpt", "gemini", "claude", "imagine", "dalle", "ask", "brainly", "imageai"],
  category: "ai",
  use: ".ai hello or .gemini hello or .imagine cat",
  async run({ XROD, m, inputCMD, text, from, isOwner }) {
    
    const prefix = ".";
    
    switch (inputCMD) {
      
      // 🤖 ChatGPT Command
      case "ai":
      case "gpt":
      case "chatgpt":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}ai your question\n\nExample: ${prefix}ai What is AI?`);
        
        await m.reply("🤔 *Thinking...*");
        try {
          const { data } = await axios.get(`https://api.siputzx.my.id/api/ai/gpt4?text=${encodeURIComponent(text)}`);
          if (data && data.data) {
            await m.reply(`🤖 *ChatGPT:*\n\n${data.data}`);
          } else {
            // Fallback API
            const { data: fallback } = await axios.get(`https://vihangayt.me/tools/chatgpt?q=${encodeURIComponent(text)}`);
            await m.reply(`🤖 *ChatGPT:*\n\n${fallback.response}`);
          }
        } catch (err) {
          await m.reply("❌ AI is busy! Try again later.");
        }
        break;
      
      // ✨ Gemini Command
      case "gemini":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}gemini your question\n\nExample: ${prefix}gemini Explain AI`);
        
        await m.reply("🧠 *Processing with Gemini...*");
        try {
          const { data } = await axios.get(`https://vihangayt.me/tools/gemini?q=${encodeURIComponent(text)}`);
          if (data && data.response) {
            await m.reply(`✨ *Gemini AI:*\n\n${data.response}`);
          } else {
            await m.reply("❌ Gemini error! Try again.");
          }
        } catch (err) {
          await m.reply("❌ Gemini API error!");
        }
        break;
      
      // 🧠 Claude Command
      case "claude":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}claude your question\n\nExample: ${prefix}claude What is consciousness?`);
        
        await m.reply("🧠 *Thinking with Claude...*");
        try {
          const { data } = await axios.get(`https://api.claude.ai/chat?q=${encodeURIComponent(text)}`);
          if (data && data.response) {
            await m.reply(`🧠 *Claude AI:*\n\n${data.response}`);
          } else {
            await m.reply("❌ Claude is busy! Try again.");
          }
        } catch (err) {
          await m.reply("❌ Claude API error! Use .ai instead.");
        }
        break;
      
      // 🎨 Imagine/DALL-E Command
      case "imagine":
      case "dalle":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}imagine your description\n\nExample: ${prefix}imagine a cute cat playing guitar`);
        
        await m.reply("🎨 *Generating image... Please wait.*");
        try {
          const { data } = await axios.get(`https://vihangayt.me/tools/dalle?q=${encodeURIComponent(text)}`);
          if (data && data.response) {
            await XROD.sendMessage(from, { image: { url: data.response }, caption: `🎨 *Generated by DALL-E*\n\nPrompt: ${text}` });
          } else {
            await m.reply("❌ Failed to generate image!");
          }
        } catch (err) {
          await m.reply("❌ Image generation error!");
        }
        break;
      
      // 🖼️ Imagine2/Stable Diffusion
      case "imagine2":
      case "sd":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}imagine2 your description\n\nExample: ${prefix}imagine2 a beautiful sunset`);
        
        await m.reply("🎨 *Generating with Stable Diffusion...*");
        try {
          const { data } = await axios.get(`https://api.stablediffusion.com/generate?prompt=${encodeURIComponent(text)}`);
          if (data && data.image) {
            await XROD.sendMessage(from, { image: { url: data.image }, caption: `🎨 *Stable Diffusion*\n\nPrompt: ${text}` });
          } else {
            await m.reply("❌ Generation failed!");
          }
        } catch (err) {
          await m.reply("❌ Stable Diffusion error! Use .imagine instead.");
        }
        break;
      
      // ❓ Ask Command (General Q&A)
      case "ask":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}ask your question\n\nExample: ${prefix}ask What is the meaning of life?`);
        
        await m.reply("🔍 *Searching for answer...*");
        try {
          const { data } = await axios.get(`https://api.ask.ai/answer?q=${encodeURIComponent(text)}`);
          if (data && data.answer) {
            await m.reply(`❓ *Answer:*\n\n${data.answer}`);
          } else {
            await m.reply("❌ No answer found! Try .ai instead.");
          }
        } catch (err) {
          await m.reply("❌ Ask API error! Use .ai.");
        }
        break;
      
      // 📚 Brainly Command
      case "brainly":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}brainly your question\n\nExample: ${prefix}brainly What is photosynthesis?`);
        
        await m.reply("📚 *Searching Brainly...*");
        try {
          const { data } = await axios.get(`https://vihangayt.me/tools/brainly?q=${encodeURIComponent(text)}`);
          if (data && data.data && data.data.length > 0) {
            let result = `📚 *Brainly Answers*\n\n`;
            for (let i = 0; i < Math.min(2, data.data.length); i++) {
              result += `❓ *Question:* ${data.data[i].question}\n`;
              result += `✅ *Answer:* ${data.data[i].answer}\n\n`;
            }
            await m.reply(result);
          } else {
            await m.reply("❌ No answers found on Brainly!");
          }
        } catch (err) {
          await m.reply("❌ Brainly error! Try again.");
        }
        break;
      
      // 🖼️ ImageAI (AI Image Generator)
      case "imageai":
        if (!text) return m.reply(`❌ *Usage:* ${prefix}imageai your description\n\nExample: ${prefix}imageai a futuristic city`);
        
        await m.reply("🎨 *Generating AI image...*");
        try {
          const { data } = await axios.get(`https://api.imgai.com/generate?prompt=${encodeURIComponent(text)}`);
          if (data && data.url) {
            await XROD.sendMessage(from, { image: { url: data.url }, caption: `🖼️ *AI Generated*\n\nPrompt: ${text}` });
          } else {
            await m.reply("❌ Failed to generate image!");
          }
        } catch (err) {
          await m.reply("❌ ImageAI error! Use .imagine instead.");
        }
        break;
      
      // 📜 AI Menu Command
      case "aimenu":
        const menu = `
╭━━━〔 🤖 AI MENU 〕━━━⬣
┃ ${prefix}ai - ChatGPT
┃ ${prefix}gemini - Google Gemini
┃ ${prefix}claude - Claude AI
┃ ${prefix}imagine - DALL-E image
┃ ${prefix}imagine2 - Stable Diffusion
┃ ${prefix}ask - Ask anything
┃ ${prefix}brainly - Brainly answer
┃ ${prefix}imageai - AI image generator
╰━━━━━━━━━━━━━━⬣

📌 *Example Usage:*
${prefix}ai What is AI?
${prefix}imagine a cute dog
${prefix}brainly What is math?
        `;
        await XROD.sendMessage(from, { text: menu });
        break;
      
      default:
        break;
    }
  }
};